### ISSUE TITLE
Suggestions for your Website going forward

### ISSUE THREAD

**Issue by hentai-chan** [Educorreia932/Website#17]
# Some Suggestions

- For your [homepage](https://educorreia932.dev/html/introduction.html): dissect the main text in at least two sub-sections with headers (also FYI the ASCII art placement is a little unfortunate because it makes it harder to read your text, at the very least reduce your frame rate at which the animation updates)
- Would be great if your [projects](https://educorreia932.dev/html/projects.html) page would link the listed projects to their respective repositories. Include a live demo where possible, and briefly explain
  - initial motivation (or the problem you intended to solve with your code)
  - main features / things you learnt
  - hindsight 20/20: what you would have done different providing you'd this again (hypothetically speaking)
- Go easy on the memes, less is more, etc.
- Big fan of your progress bar at the bottom of your homepage, haven't seen this one yet
- You will hear different opinions about this point but from what I have been told it is generally recommended to not link your social accounts on your portfolio page

# Additional Resources

- I'd recommend watching some of these reviews on YouTube about what to look out for with respect to your current design, you did some things rights, others not so much: one thing is for sure, your design is very interesting. 
  - [This playlist but Flux is really great, it's also the first search result for 'portfolio website review'](https://www.youtube.com/watch?v=4QU7bd9tgY4&list=PLXC_gcsKLD6kUJ7p9JDfAJ905bImp4CXk)
  - [Joshua Flake is also alright, although sometimes his answers are too convoluted](https://www.youtube.com/watch?v=xLxm9RP1GbA)
  - [Long video but drops some solid lessons on fundamental design principles](https://www.youtube.com/watch?v=1toVDr9dYbM)

**Comment by Educorreia932** [comment]
Thank you for yoru suggestions, I really appreaciate them and I'll try to improve my website as best as I can based on them!
