### ISSUE TITLE
Published Spotify Secrets

### ISSUE THREAD

**Issue by LiamEarle** [Educorreia932/Website#8]
Hey Educorreia932,

I was just looking through the source for your Spotify Statistics application and noticed that you are committing your Spotify client secrets. You may want to look into including these as an environment variable or .env file (removing it from your git) so they are not published.

Also, you may want to revoke and regenerate your client secrets.

Kind Regards,

L.

https://github.com/Educorreia932/Website/blob/22bcbe4613db4a3223ecf743198b8c41a2e00e57/spotify/web-api-auth-examples/authorization_code/app.js#L18

**Comment by Educorreia932** [comment]
I've generated a new one, thank you
